# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10e9fb6e2f08f5f2c40ed8cef2b7a10219dedbef123049b0047e4f6bd312d0910805d7f778d1e202fda0fdd14b3b6758a78f43fbb543d8b3618679facc3d7c4b

test:
  secret_key_base: f9248fad84900d779ae2dc1a7cf232748c4a69a7af2edbeaf9e5a873aad476632f887392bd5b2553418c9c3cc9505e2cfd91d26386194452769c5399d0295855

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
